stages:
  get_mitre_data:
    cmd: python src/get_mitre_data.py params.yaml
    deps:
    - src/get_mitre_data.py
    - ${get_data.mitre_attack_fn}
    params:  
    - get_data.divide_paras
    outs:
    - ${get_data.data_mitre_fn}
    - ${get_data.data_mitre_attack_proc_fn}
    - ${get_data.label2tactic_fn}
  get_add_data:
    cmd: python src/get_add_data.py params.yaml
    deps:
    - ${get_data.data_mitre_fn}
    - ${get_data.tram_fn}
    - ${get_data.data_mitre_attack_proc_fn}
    - ${get_data.label2tactic_fn}
    - ${get_data.mitre_alt_fn}
    - ${get_data.rep_dn}
    - src/get_add_data.py
    params:
    - get_data.use_tram_f
    - get_data.use_reports_f
    - get_data.add_empty_reports
    - get_data.use_alt_mitre
    - get_data.target
    - get_data.data_fn
    outs:
    - ${get_data.data_fn}
  manual_data_filter:
    cmd: python src/manual_data_filter.py params.yaml
    deps:
    - ${get_data.data_fn}
    - src/manual_data_filter.py
    outs:
    - ${get_data.data_filt_fn}
  text_preprocess:
    cmd: python src/prep.py params.yaml
    deps:
    - src/prep.py
    - ${get_data.data_filt_fn}
    params:
    - prep_text.lower
    - prep_text.stop_words
    - prep_text.min_len_token
    - prep_text.max_len_token
    - prep_text.save_only_words
    - prep_text.stem_lemm
    - prep_text.ttp_counts_thresh  
    - prep_text.labelled_text_only
    outs:
    - ${prep_text.prep_fn}
    - ${prep_text.mlb_fn}
    - ${prep_text.ttp_mlb_fn}
  feature_generation:
    cmd: python src/feat_gen.py params.yaml
    deps:
    - src/feat_gen.py
    - src/spec_funcs.py
    - ${prep_text.prep_fn}
    - ${prep_text.mlb_fn}
    params:
    - feat_gen.feat_strategy
    - feat_gen.binary
    - val_ts_size
    - val_only_proc
    - feat_gen.max_features
    - feat_gen.min_df
    - feat_gen.max_df
    - feat_gen.logreg_c
    - feat_gen.ind_sel_tree_max_depth
    - feat_gen.add_individual_thresh
    - feat_gen.tree_maxdepth
    - seed  
    outs:
    - ${feat_gen.feat_fn}
    - ${feat_gen.data_fn}
    - ${feat_gen.vec_fn}
  feature_engineering:
      cmd: python src/feat_eng.py params.yaml
      deps:
      - src/feat_eng.py
      - ${feat_gen.feat_fn}
      - ${feat_gen.data_fn}
      - ${feat_gen.vec_fn}
      params:
      - feat_eng.tfidf_dim
      - feat_eng.add_clust_feat
      - feat_eng.topic_algo
      - feat_eng.add_topic_feat
      - feat_eng.add_ind_cols
      - seed
      outs:
      - ${feat_eng.feat_final_fn}
  train_eval_model:
      cmd: python src/train_eval_model.py params.yaml
      deps:
      - src/train_eval_model.py
      - ${feat_eng.feat_final_fn}
      params:
      - train_eval_model.chain
      - train_eval_model.model
      - train_eval_model.balanced
      - train_eval_model.opt_metric
      - train_eval_model.attack_clf
      - seed
      metrics:
      - ${train_eval_model.metrics_fn}
      outs:
      - ${train_eval_model.opt_metric_fn}
      - ${train_eval_model.by_class_metric_fn}
      - ${train_eval_model.conf_df_fn}
      - ${train_eval_model.conf_matrix_fn}
      - ${train_eval_model.conf_matrix_main_er_fn}
      - ${train_eval_model.model_fn}
      - ${train_eval_model.add_metrics_fn}
  train_conv_model:
     cmd: dvc repro dvc_pipes/train_conv_emb/dvc.yaml
  train_bert_model:
     cmd: dvc repro dvc_pipes/bert/dvc.yaml