get_data:
  mitre_attack_fn: data/external/enterprise-attack.json
  tram_fn: data/external/multi_label.json
  mitre_alt_fn: data/external/dataset.txt
  use_alt_mitre: false
  rep_dn: data/external/rep_dn
  use_tram_f: true
  use_reports_f: false
  add_empty_reports: false
  divide_paras: true
  target: tactic
  data_mitre_fn: data/interim/mitre.csv
  data_mitre_attack_proc_fn: data/interim/mitre_attack.csv
  label2tactic_fn: data/interim/label2tactic.json
  data_fn: data/interim/mitre_full_df.csv
  data_filt_fn: data/interim/mitre_full_filt_df.csv
prep_text:
  lower: false
  stop_words: false  # True - english stopwords or None - not use
  min_len_token: 3
  max_len_token: 10
  save_only_words: false
  stem_lemm: stem    # stem or null
  labelled_text_only: false
  prep_fn: data/interim/prep_df.csv
  mlb_fn: data/interim/mlb.pkl
feat_gen:
  feat_strategy: count   #'tfidf' or 'count'
  binary: false # true or false
  min_df: 10
  max_df: 0.3
  max_features:  # null or int of total features to get
  logreg_c: 0.05
  tree_maxdepth: 2
  add_individual_thresh: 0.95 # null if not use individual
  feat_fn: data/interim/feat_df.csv
  data_fn: data/interim/data_df.csv
  vec_fn: data/interim/vec.pkl
feat_eng:
  tfidf_dim:       # null or int to crop dimension
  add_clust_feat: false # false or true - use several k position to predict cluster
  topic_algo: lsa   # lsa or lda
  add_topic_feat:   # null or int - number of topics
  add_ind_cols: true  # true or false, whether to add cols with T...
  feat_final_fn: data/out/feat_final_df.csv
train_eval_model:
  chain: true # true use ClassifierChain, false - OneVsRestClassifier
  model: logreg     # tree, forest, knn, logreg, boost
  balanced:        # balanced or null
  opt_metric: f1
  opt_metric_fn: data/out/opt_metric.csv
  by_class_metric_fn: data/out/by_class_metric.csv
  attack_clf: inc   # nan, if alone is included in features and gives pred of empty class, if other string is included in features
  conf_df_fn: data/out/conf_df.csv
  conf_matrix_fn: data/out/confusion_matrix.png
  metrics_fn: data/out/m.json
  add_metrics_fn: data/out/m_other.json
  model_fn: data/out/model.pkl
seed: 0
val_ts_size: 0.15
val_only_proc: false
use_only_proc: false
